#MYsql
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=URL_BANCO
spring.datasource.username=USUARIO
spring.datasource.password=SENHA

#Exibe os comandos SQL
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace

spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jackson.serialization.fail-on-empty-beans=false